documents/documents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("documents/doc-admin/", admin.site.urls),
    path("", include("instruction.urls")),
    path("manuals/", include("manuals.urls")),
    path("user/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    )
    urlpatterns.extend(
        static(settings.LOGGING_URL, document_root=settings.LOGGING_ROOT)
    )

documents/instruction/urls.py
from django.urls import path

from .views import (
    AddFileProjectView,
    CreateDeviceView,
    DeviceDetailView,
    IdCRMDetailView,
    InstructionFileView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectListView,
    SearchProjectView,
)

app_name = "project"

urlpatterns = [
    path("", ProjectListView.as_view(), name="index"),
    path(
        "product/<slug:slug>/detail", ProjectDetailView.as_view(), name="product-detail"
    ),
    path("product/create", ProjectCreateView.as_view(), name="product-create"),
    path(
        "product/<slug:slug>/add_files", AddFileProjectView.as_view(), name="add-files"
    ),
    path("id_crm/<int:crm_id>/detail", IdCRMDetailView.as_view(), name="id_crm-detail"),
    path(
        "product/<slug:slug>/create", CreateDeviceView.as_view(), name="device-create"
    ),
    path("device/<slug:slug>/detail", DeviceDetailView.as_view(), name="device-detail"),
    path("product/search", SearchProjectView.as_view(), name="search"),
    path("documents/instructions", InstructionFileView.as_view(), name="instructions"),
    # path('brand', BrandView.as_view(), name='brand-list'),
    # path('brand/<slug:slug>', BrandDetailView.as_view(), name='brand-detail'),
    # path('documents/instructions/add', AddedInstructionView.as_view(), name='instruction-add'),
]

documents/manuals/urls.py
from django.urls import path

from .views import BrandDetailView, BrandView

app_name = "manual"

urlpatterns = [
    path("", BrandView.as_view(), name="brand-list"),
    path("detail/<slug:slug>", BrandDetailView.as_view(), name="brand-detail"),
]

documents/users/urls.py
from django.urls import path

from .views import LoginUserView, LogoutUserView, RegisterUserView

app_name = "users"

urlpatterns = [
    path("login/", LoginUserView.as_view(), name="login"),
    path("logout/", LogoutUserView.as_view(), name="logout"),
    path("register/", RegisterUserView.as_view(), name="register"),
]

documents/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'access/img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'access/fonts/Wolgadeutsche.ttf' %}">
    <link rel="stylesheet" href="{% static 'access/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <title>{{ title }}</title>
</head>

<body>
    {% include 'base/header.html' %}
    {% block tester %}
    <div class="tester">
        <span>Данный проект еще в разработке. Некоторе ресурсы могут быть не доступны!</span>
    </div>
    {% endblock %}
    {% block breadcrumbs %}{% endblock %}

    {% block content %}
    {% endblock %}
    
    
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <!-- JavaScript and Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="{% static 'access/js/main.js' %}"></script>

    <script>
        //    для активного отображения подсказок на JavaScript
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
        
        //   для активного отображения подсказок на jQuery 
        // $(document).ready(function () {$('[data-bs-toggle="tooltip"]').tooltip(); });
    </script>
    <script>
        // скрипт присваеивает полю с id_file аттрибут multiple со значением True
        // для мульти загрузок файлов
        $(document).ready(function () {
            $('#id_file').attr("multiple", "true");
        })
    </script>
</body>

</html>

documents/templates/base/empty_data.html
{% load i18n static %}

<div class="position-absolute top-50 start-50 translate-middle auth-content">
    <div class="signin-form">
        <div class="modal-header auth-header">
            <h2 class="modal-title auth-title">Данных пока нет</h2>
            <a style="padding: 15px" href="{{ request.META.HTTP_REFERER }}" type="button"
               class="btn-close position-absolute top-0 end-0"></a>
               <img class="data-empty" src="{% static 'access/img/wayne-tumbleweed.gif' %}"  alt="Пусто">
        </div>
        <div class="form-auth">
            <div class="flex" style="justify-content: flex-end;">
                <a type="button" class="btn btn-primary" href="{{ request.META.HTTP_REFERER }}">Ok</a>
            </div>
        </div>
    </div>
</div>

documents/templates/base/header.html
{% load i18n static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img class="logo-icon"
                src="https://cdn-ru.bitrix24.ru/b13049348/bitrix24/89b/89b1c30f2e5c56d978efed652fa55b7a/logo_VrI4ahUF.png"
                alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
            aria-controls="navbarScroll" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <form class="d-flex searche-form" role="search" action="{% url 'project:search' %}" method="get" id="search"
                name="form">
                <input id="btn_search" class="form-control me-2" type="search" name="search"
                    placeholder="Имя проекта или ID" aria-label="поиск">
                <button class="btn btn-outline-success" type="submit" onclick="searchID()">
                    {% translate 'Найти' %}
                </button>
            </form>
            <ul class="nav nav-underline navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll top-menu"
                style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'manual:brand-list' %}"
                    data-bs-toggle="tooltip" data-bs-placement="bottom"
                    data-bs-title="РЭ и ПО на оборудование">
                        {% translate 'Документация' %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://rinecogroup.bitrix24.ru/" target="_blank"
                    data-bs-toggle="tooltip" data-bs-placement="bottom"
                    data-bs-title="rineco.bitrix24">
                        {% translate 'Bitrix' %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"
                    data-bs-toggle="tooltip" data-bs-placement="bottom"
                    data-bs-title="О нас">
                    {% translate 'О нас' %}
                    </a>
                </li>
                {% if user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project:product-create' %}"
                    data-bs-toggle="tooltip" data-bs-placement="bottom"
                    data-bs-title="Добавить новый проект">{% translate 'Добавить' %}</a>
                </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
            <ul class="nav nav-underline navbar-nav">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle termo" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <img class="me-4" src="{% static 'access/icon/user-regular.svg' %}" width="14" alt="10">
                        {% if user.first_name and user.last_name %}
                        {{ user.first_name }} {{ user.last_name }}
                        {% else %}
                        {{ user.username }}
                        {% endif %}
                    </button>
                    <ul class="dropdown-menu auth">
                        <li><a class="dropdown-item" href="#">{% translate 'Редактировать' %}</a></li>
                        {% if user.is_staff %}
                        <li>
                            <a class="dropdown-item" href="{% url 'admin:index' %}">
                                {% translate 'Администрирование' %}
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                                {% translate 'Памятка' %}
                            </a>
                        </li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">{% translate 'Выйти' %}</a>
                        </li>
                    </ul>
                </div>
            </ul>
            {% else %}
            <ul class="nav nav-underline navbar-nav">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle not-auth" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <img src="{% static 'access/icon/user-regular.svg' %}" width="20" alt="12">
                    </button>
                    <ul class="dropdown-menu not-auth">
                        <li><a class="dropdown-item signin-link" href="{% url 'users:login' %}">
                                {% translate 'Авторизация' %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:register' %}">{% translate 'Регистрация' %}</a>
                        </li>
                    </ul>
                </div>
            </ul>
            {% endif %}
        </div>
    </div>
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Памятка</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
                <div class="modal-body">
                    <h2 class="fs-5" style="color: black !important;">При загрузке данных из файла</h2>
                    <p>
                        При добавлении продуктов или оборудования требуется соблюдать их очередность. <br>
                        В первую очередь:
                        <ol>
                            <li>Добавляется Производитель ("Brand");</li>
                            <li>Добавляется Проект ("Project");</li>
                            <li>Добавляется тип Сети ("Network");</li>
                        </ol>
                        Дальнейшее добавление данных не имеют очередности...
                    </p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Ok</button>
            </div>
            </div>
        </div>
    </div>
</nav>