documents/documents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("documents/doc-admin/", admin.site.urls),
    path("", include("instruction.urls")),
    path("manuals/", include("manuals.urls")),
    path("user/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    )
    urlpatterns.extend(
        static(settings.LOGGING_URL, document_root=settings.LOGGING_ROOT)
    )

documents/instruction/urls.py
from django.urls import path

from .views import (
    AddFileProjectView,
    CreateDeviceView,
    DeviceDetailView,
    IdCRMDetailView,
    InstructionFileView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectListView,
    SearchProjectView,
)

app_name = "project"

urlpatterns = [
    path("", ProjectListView.as_view(), name="index"),
    path(
        "product/<slug:slug>/detail", ProjectDetailView.as_view(), name="product-detail"
    ),
    path("product/create", ProjectCreateView.as_view(), name="product-create"),
    path(
        "product/<slug:slug>/add_files", AddFileProjectView.as_view(), name="add-files"
    ),
    path("id_crm/<int:crm_id>/detail", IdCRMDetailView.as_view(), name="id_crm-detail"),
    path(
        "product/<slug:slug>/create", CreateDeviceView.as_view(), name="device-create"
    ),
    path("device/<slug:slug>/detail", DeviceDetailView.as_view(), name="device-detail"),
    path("product/search", SearchProjectView.as_view(), name="search"),
    path("documents/instructions", InstructionFileView.as_view(), name="instructions"),
    # path('brand', BrandView.as_view(), name='brand-list'),
    # path('brand/<slug:slug>', BrandDetailView.as_view(), name='brand-detail'),
    # path('documents/instructions/add', AddedInstructionView.as_view(), name='instruction-add'),
]

documents/users/urls.py
from django.urls import path

from .views import LoginUserView, LogoutUserView, RegisterUserView

app_name = "users"

urlpatterns = [
    path("login/", LoginUserView.as_view(), name="login"),
    path("logout/", LogoutUserView.as_view(), name="logout"),
    path("register/", RegisterUserView.as_view(), name="register"),
]

documents/instruction/models.py
from django.db import models
from django.urls import reverse

# from imagekit.models import ProcessedImageField
# from imagekit.processors import ResizeToFill


def path_to_file_configs(instance: "FileDevice", filename: str) -> str:
    """
    The function generates a path based on the name of the file with the configs.

    :param instance: object File
    :param filename: name file
    :return: str - path to save
    """
    return f"configs/{instance.device_id.name}/{filename}"


def path_to_file_report(instance: "FileProject", filename: str) -> str:
    """
    The function generates a path based on the name of the file with the report.

    :param instance: object File
    :param filename: name file
    :return: str - path to save
    """
    return f"photos/{instance.project_id}/{filename}"


def path_to_file(instance: "FileProject", filename: str) -> str:
    """
    The function generates a path based on the name of the file .

    :param instance: object FileProject
    :param filename: name FileProject
    :return: str - path to save
    """
    return f"files/{instance.project_id}/{filename}"


def path_to_zip_file(instance: "ArchiveFile", filename: str) -> str:
    """
    The function generates a path based on the name of the file .

    :param instance: object ArchiveFile
    :param filename: name file
    :return: str - path to save
    """
    return f"zip_files/{instance.project_id}/{filename}"


class Project(models.Model):
    """
    The class describes the Project model
    """

    crm_id = models.CharField(max_length=10, verbose_name="ID CRM", db_index=True)
    company = models.CharField(max_length=120, verbose_name="Company")
    project = models.CharField(
        max_length=120,
        verbose_name="Project",
    )
    slug = models.SlugField(
        max_length=200, verbose_name="URL", db_index=True, unique=True
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Date updated")
    description = models.TextField(verbose_name="Info", default=" ", blank=True)
    archive = models.BooleanField(default=False, verbose_name="Archive", blank=True)

    def __str__(self) -> str:
        return f"{self.crm_id}-{self.project}"

    def get_absolute_url(self):
        return reverse("project:product-detail", kwargs={"slug": self.slug})

    class Meta:
        db_table = "project"
        verbose_name = "project"
        verbose_name_plural = "projects"


class Device(models.Model):
    """
    The class describes the Device model
    """

    project_id = models.ForeignKey(
        "Project",
        on_delete=models.CASCADE,
        verbose_name="Project",
        blank=True,
        default="not project",  # type: ignore
    )
    name = models.CharField(max_length=80, verbose_name="Device", db_index=True)
    designation = models.CharField(
        max_length=100, verbose_name="Обозначение", blank=True
    )
    serial_num = models.CharField(
        max_length=25, verbose_name="Serial number", default="n/a", blank=True
    )
    slug = models.SlugField(max_length=150, verbose_name="URL", unique=True)
    description = models.TextField(
        verbose_name="Description", blank=True, default="Пока данных нет"
    )
    termodate = models.BooleanField(default=False, verbose_name="Termo date")
    network_id = models.ManyToManyField("Network", verbose_name="Network")

    def __str__(self) -> str:
        if self.serial_num:
            return f"{self.designation}-{self.serial_num}"
        else:
            return f"{self.name}"

    def get_absolute_url(self):
        return reverse("project:device-detail", kwargs={"slug": self.slug})

    class Meta:
        db_table = "devices"
        verbose_name = "device"
        verbose_name_plural = "devices"


class FileDevice(models.Model):
    """
    The class describes the InstructionFile model
    """

    device_id = models.ForeignKey(
        Device,
        on_delete=models.CASCADE,
        verbose_name="Device",
        related_name="devices_files",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Date updated")
    file_configs = models.FileField(
        verbose_name="Файлы", upload_to=path_to_file_configs, blank=True
    )
    # file_configs = ProcessedImageField(
    #     upload_to = path_to_file_configs,
    #     verbose_name = 'Photo config',
    #     blank = True,
    #     options={'quantity': 100},
    #     format= 'JPEG',
    #     processors=[ResizeToFill(850, 380)]
    #     )

    def __str__(self) -> str:
        return f"{self.device_id.name}"

    class Meta:
        db_table = "file_device"
        verbose_name = "photo"
        verbose_name_plural = "photos"


class Network(models.Model):
    """
    The class describes the InstructionFile model
    """

    name = models.CharField(max_length=120, verbose_name="Name", db_index=True)
    slug = models.SlugField(max_length=120, verbose_name="URL", unique=True)
    description = models.TextField(verbose_name="Description", blank=True, default=" ")

    def __str__(self) -> str:
        return f"{self.name}"

    class Meta:
        db_table = "networks"
        verbose_name = "network"
        verbose_name_plural = "networks"


class Settings(models.Model):
    """
    The class describes the Settings model
    """

    class Speed(models.IntegerChoices):
        NOT_USED = 0
        S_1200 = 1200, "1200"
        S_2400 = 2400, "2400"
        S_4800 = 4800, "4800"
        S_9600 = 9600, "9600"
        S_19200 = 19200, "19200"
        S_38400 = 38400, "38400"
        S_57600 = 57600, "57600"
        S_115200 = 115200, "115200"

    class Paritet(models.TextChoices):
        NOT_USED = "-"
        EVEN = "E"
        NONE = "N"
        ODD = "O"

    class Bits(models.IntegerChoices):
        NOT_USED = 0
        SEVEN = 7, "7"
        EIGHT = 8, "8"
        NINE = 9, "9"

    class StopBit(models.IntegerChoices):
        NOT_USED = 0
        ONE = 1, "1"
        TWO = 2, "2"

    interface = models.ForeignKey(
        Network, verbose_name="Interface", on_delete=models.CASCADE
    )
    device = models.ForeignKey(
        Device,
        on_delete=models.CASCADE,
        verbose_name="Device",
        related_name="devices_settings",
    )
    slug = models.SlugField(
        max_length=50, verbose_name="URL", db_index=True, unique=True
    )
    slave_id = models.IntegerField(verbose_name="Slave ID", blank=True, null=True)
    speed = models.IntegerField(verbose_name="Speed", default=0, choices=Speed.choices)
    paritet = models.CharField(
        max_length=1, verbose_name="Paritet", default="-", choices=Paritet.choices
    )
    bit = models.IntegerField(verbose_name="Bits", default=0, choices=Bits.choices)
    stop_bit = models.IntegerField(
        verbose_name="Stop bit", default=0, choices=StopBit.choices
    )
    ip_address = models.CharField(
        max_length=15, verbose_name="IP address", default="not used"
    )
    mask = models.CharField(max_length=15, verbose_name="Mask", default="not used")
    gateway = models.CharField(
        max_length=15, verbose_name="Gateway", default="not used"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Date updated")
    description = models.TextField(verbose_name="Description", default=" ", blank=True)

    def __str__(self) -> str:
        return f"{self.interface} for {self.device}"

    class Meta:
        db_table = "settings"
        verbose_name = "setting"
        verbose_name_plural = "settings"


class WaveSensor(models.Model):
    """
    The class describes the WaveSensor model
    """

    device_id = models.ForeignKey(
        Device, on_delete=models.CASCADE, verbose_name="Binding", related_name="devices"
    )
    name_rkd = models.CharField(
        max_length=15, verbose_name="Desicn to RKD", db_index=True
    )  # обозначение по РКД
    description = models.CharField(
        max_length=80, verbose_name="Name equipment"
    )  # наименование оборудования
    group = models.CharField(max_length=30, verbose_name="Group")  # группа датчиков
    install = models.IntegerField(
        verbose_name="Column install"
    )  # установлено в колонне
    serial_number = models.CharField(
        max_length=30, verbose_name="Serial number"
    )  # серийный номер
    register = models.IntegerField(verbose_name="Register")  # регистр
    temp_warning = models.CharField(
        max_length=3, verbose_name="Temperature warning", default="85"
    )  # Предупреждение
    temp_error = models.CharField(
        max_length=3, verbose_name="Temperature over", default="90"
    )  # Перегрев

    def __str__(self) -> str:
        return f"{self.name_rkd}"

    class Meta:
        db_table = "wavesensors"
        verbose_name = "sensor"
        verbose_name_plural = "sensors"


class FileProject(models.Model):
    """ """

    project_id = models.ForeignKey(
        Project, on_delete=models.CASCADE, verbose_name="Проект", related_name="files"
    )
    name = models.CharField(verbose_name="Название", max_length=110, db_index=True)
    file = models.FileField(verbose_name="Файл", upload_to=path_to_file, blank=True)
    file_photos = models.ImageField(
        verbose_name="Photo", upload_to=path_to_file_report, blank=True  # type: ignore
    )
    # file_photos = ProcessedImageField(
    #     upload_to = path_to_file_report,
    #     verbose_name = 'Photo',
    #     blank = True,
    #     options={'quantity': 60},
    #     format= 'JPEG',
    #     processors=[ResizeToFill(310, 280, anchor=False)]
    #     )

    def __str__(self) -> str:
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse()  # type: ignore

    class Meta:
        db_table = "file_project"

documents/templates/device/create_device.html
{% extends 'base/base.html' %}
{% load i18n static %}
{% load devices_tag %}

<!-- Хлебные крошки -->
{% block breadcrumbs %}
{% project_breadcrumb slug as product %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'project:index' %}">Главная</a></li>
        <li class="breadcrumb-item active " aria-current="page">
            <a href="{% url 'project:id_crm-detail' product.crm_id %}">
                ID-CRM {{ product.crm_id }}
            </a>
        </li>
        <li class="breadcrumb-item active " aria-current="page">
            <a href="{% url 'project:product-detail' product.slug %}">
            {{ product.project }}
            </a>
        </li>
        <li class="breadcrumb-item active " aria-current="page">Новое устройство</li>
    </ol>
</nav>
{% endblock %}


{% block content %}
<div class="device-create"> 
<div class="position-absolute top-50 start-50 translate-middle auth-content">
    <div class="signin-form ">
        <div class="modal-header auth-header">
            <h2 class="modal-title auth-title h4">{{ title }}</h2>
            <a style="padding: 15px" href="{% url 'project:product-detail' slug %}" type="button"
                class="btn-close position-absolute top-0 end-0"></a>
        </div>
        {% include "form_create/form_create.html" %}
    </div>
</div>
</div>
{% endblock %}

documents/templates/device/delete_device.html
{% extends 'base/base.html' %}
{% load i18n static %}
{% load devices_tag %}

{% block content %}
<div class="position-absolute top-50 start-50 translate-middle auth-content">
    <div class="signin-form">
        <div class="modal-header auth-header">
            <h2 class="modal-title auth-title">Действительно хотите удалить</h2>
            <a style="padding: 15px" href="{{ request.META.HTTP_REFERER }}" type="button"
               class="btn-close position-absolute top-0 end-0">
            </a>
        </div>
        <div class="form-auth">
            <div class="flex" style="justify-content: flex-end;">
                <form action="{% url 'project:product-detail' slug=product_slug %}" method="post">
                    {% csrf_token %}
                    <button type="submit">
                        Подтвердить
                    </button>
                </form>
                <!-- <a type="button" class="btn btn-primary" href="{{ request.META.HTTP_REFERER }}">Ok</a> -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

documents/templates/device/device_detail.html
{% extends 'base/base.html' %}
{% load i18n static %}

<!-- Хлебные крошки -->
{% block breadcrumbs %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'project:index' %}">Главная</a></li>
        <li class="breadcrumb-item active " aria-current="page">
            <a href="{% url 'project:id_crm-detail' device.project_id.crm_id %}">
                ID-CRM {{ device.project_id.crm_id }}
            </a>
        </li>
        <li class="breadcrumb-item active " aria-current="page"><a
                href="{%  url 'project:product-detail' device.project_id.slug %}">{{ device.project_id.project }}</a>
        </li>
        <li class="breadcrumb-item active " aria-current="page">{{ device.name }}</li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    <div class="flex device-title">
        <div class="flex icon-title">
            <h2>{{ device.name }} - № {{ device.serial_num }}</h2>
            <img src="{% static 'access/icon/circle-info-solid.svg' %}" width="25px" alt="Помощь"
            data-bs-toggle="tooltip" data-bs-placement="bottom"
            data-bs-custom-class="custom-tooltip"
            data-bs-title="{% if device.description %}{{ device.description }}{% endif %}">
        </div>
        <span>ID - {{ device.project_id.crm_id }}</span>
    </div>
    <span class="strong">Сетевые параметры</span>
    <div class="flex setting-content">
        <table class="table table-light table-hover caption-top table-setting">
            <thead>
                <tr>
                    <th scope="col">Наименование</th>
                    <th scope="col">Значение</th>
                </tr>
            </thead>
            {% with device.devices_settings.first as set %}
            <tbody>
                <tr>
                    <td>Наименование по РКД:</td>
                    <td>{{ device.designation }}</td>
                </tr>
                <tr>
                    <td>Протокол:</td>
                    <td>{{ device.network_id.first.name }}</td>
                </tr>
                {% if "485" in device.network_id.first.name %}
                <tr>
                    <td>Slave ID:</td>
                    <td>{% if set.slave_id %}{{ set.slave_id }}{% else %}--{% endif %}</td>
                </tr>
                <tr>
                    <td>Speed:</td>
                    <td>{% if set.speed %}{{ set.speed }} b/s{% else %}--{% endif %}</td>
                </tr>
                <tr>
                    <td>Paritet:</td>
                    <td>{% if set.get_paritet_display %}{{ set.get_paritet_display }}{% else %}--{% endif %}</td>
                </tr>
                <tr>
                    <td>Bits:</td>
                    <td>{% if set.bit %}{{ set.bit }}{% else %}--{% endif %}</td>
                </tr>
                <tr>
                    <td>Stop bit:</td>
                    <td>{% if set.stop_bit %}{{ set.stop_bit }}{% else %}--{% endif %}</td>
                </tr>
                {% else %}
                <td>IP Address:</td>
                <td>{% if set.ip_address %}{{ set.ip_address }}{% else %}--{% endif %}</td>
                </tr>
                <tr>
                    <td>Mask:</td>
                    <td>{% if set.mask %}{{ set.mask }}{% else %}--{% endif %}</td>
                </tr>
                <tr>
                    <td>Gateway:</td>
                    <td>{% if set.gateway %}{{ set.gateway }}{% else %}--{% endif %}</td>
                </tr>
                {% endif %}
            </tbody>
            {% endwith %}
        </table>
        <div class="setting-info">
            <div class="container overflow-hidden text-center">
                <div class="row gy-5">
                    {% if device.devices.all %}
                    <div class="col-6">
                        <div class="p-2"><span>Карта датчиков</span></div>
                    </div>
                    <!-- Кнопка-триггер модального окна -->
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Открыть список датчиков
                    </button>
                    {% endif %}
                    <div class="col-10">
                        <div class="p-2"><span>Настроить {{ device }}</span></div>
                    </div>
                    <a type="button" class="btn btn-primary" href="#">
                        Настроить сетевые параметры
                    </a>
                    <!-- Модальное окно -->
                    <div class="modal fade " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                        <div class="modal-dialog  modal-dialog-scrollable" style="max-width: 50%;">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel">{{ device }}</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Закрыть"></button>
                                </div>
                                <div class="modal-body">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th scope="col">По РКД</th>
                                                <th scope="col">Назначение</th>
                                                <th scope="col">ID</th>
                                                <th scope="col">Серийный №</th>
                                                <th scope="col">Колонна №</th>
                                            </tr>
                                        </thead>
                                        {% for sensor in device.devices.all %}
                                        <tbody>
                                            <tr>
                                                <td class="setting-color" id="{{ sensor.description }}">
                                                    {{ sensor.name_rkd }}
                                                </td>
                                                <td class="setting-color" id="{{ sensor.description }}">
                                                    {{ sensor.group }}
                                                </td>
                                                <td class="setting-color" id="{{ sensor.description }}">
                                                    {{ sensor.register }}
                                                </td>
                                                <td class="setting-color" id="{{ sensor.description }}">
                                                    {{ sensor.serial_number }}
                                                </td>
                                                <td class="setting-color" id="{{ sensor.description }}">
                                                    {{ sensor.install }}
                                                </td>
                                            </tr>
                                        </tbody>
                                        {% endfor %}
                                    </table>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">OK</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}