documents/documents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("documents/doc-admin/", admin.site.urls),
    path("", include("instruction.urls")),
    path("manuals/", include("manuals.urls")),
    path("user/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    )
    urlpatterns.extend(
        static(settings.LOGGING_URL, document_root=settings.LOGGING_ROOT)
    )

documents/instruction/urls.py
from django.urls import path

from .views import (
    AddFileProjectView,
    CreateDeviceView,
    DeviceDetailView,
    IdCRMDetailView,
    InstructionFileView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectListView,
    SearchProjectView,
)

app_name = "project"

urlpatterns = [
    path("", ProjectListView.as_view(), name="index"),
    path(
        "product/<slug:slug>/detail", ProjectDetailView.as_view(), name="product-detail"
    ),
    path("product/create", ProjectCreateView.as_view(), name="product-create"),
    path(
        "product/<slug:slug>/add_files", AddFileProjectView.as_view(), name="add-files"
    ),
    path("id_crm/<int:crm_id>/detail", IdCRMDetailView.as_view(), name="id_crm-detail"),
    path(
        "product/<slug:slug>/create", CreateDeviceView.as_view(), name="device-create"
    ),
    path("device/<slug:slug>/detail", DeviceDetailView.as_view(), name="device-detail"),
    path("product/search", SearchProjectView.as_view(), name="search"),
    path("documents/instructions", InstructionFileView.as_view(), name="instructions"),
    # path('brand', BrandView.as_view(), name='brand-list'),
    # path('brand/<slug:slug>', BrandDetailView.as_view(), name='brand-detail'),
    # path('documents/instructions/add', AddedInstructionView.as_view(), name='instruction-add'),
]

documents/users/urls.py
from django.urls import path

from .views import LoginUserView, LogoutUserView, RegisterUserView

app_name = "users"

urlpatterns = [
    path("login/", LoginUserView.as_view(), name="login"),
    path("logout/", LogoutUserView.as_view(), name="logout"),
    path("register/", RegisterUserView.as_view(), name="register"),
]

documents/instruction/models.py
from django.db import models
from django.urls import reverse

# from imagekit.models import ProcessedImageField
# from imagekit.processors import ResizeToFill


def path_to_file_configs(instance: "FileDevice", filename: str) -> str:
    """
    The function generates a path based on the name of the file with the configs.

    :param instance: object File
    :param filename: name file
    :return: str - path to save
    """
    return f"configs/{instance.device_id.name}/{filename}"


def path_to_file_report(instance: "FileProject", filename: str) -> str:
    """
    The function generates a path based on the name of the file with the report.

    :param instance: object File
    :param filename: name file
    :return: str - path to save
    """
    return f"photos/{instance.project_id}/{filename}"


def path_to_file(instance: "FileProject", filename: str) -> str:
    """
    The function generates a path based on the name of the file .

    :param instance: object FileProject
    :param filename: name FileProject
    :return: str - path to save
    """
    return f"files/{instance.project_id}/{filename}"


def path_to_zip_file(instance: "ArchiveFile", filename: str) -> str:
    """
    The function generates a path based on the name of the file .

    :param instance: object ArchiveFile
    :param filename: name file
    :return: str - path to save
    """
    return f"zip_files/{instance.project_id}/{filename}"


class Project(models.Model):
    """
    The class describes the Project model
    """

    crm_id = models.CharField(max_length=10, verbose_name="ID CRM", db_index=True)
    company = models.CharField(max_length=120, verbose_name="Company")
    project = models.CharField(
        max_length=120,
        verbose_name="Project",
    )
    slug = models.SlugField(
        max_length=200, verbose_name="URL", db_index=True, unique=True
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Date updated")
    description = models.TextField(verbose_name="Info", default=" ", blank=True)
    archive = models.BooleanField(default=False, verbose_name="Archive", blank=True)

    def __str__(self) -> str:
        return f"{self.crm_id}-{self.project}"

    def get_absolute_url(self):
        return reverse("project:product-detail", kwargs={"slug": self.slug})

    class Meta:
        db_table = "project"
        verbose_name = "project"
        verbose_name_plural = "projects"


class Device(models.Model):
    """
    The class describes the Device model
    """

    project_id = models.ForeignKey(
        "Project",
        on_delete=models.CASCADE,
        verbose_name="Project",
        blank=True,
        default="not project",  # type: ignore
    )
    name = models.CharField(max_length=80, verbose_name="Device", db_index=True)
    designation = models.CharField(
        max_length=100, verbose_name="Обозначение", blank=True
    )
    serial_num = models.CharField(
        max_length=25, verbose_name="Serial number", default="n/a", blank=True
    )
    slug = models.SlugField(max_length=150, verbose_name="URL", unique=True)
    description = models.TextField(
        verbose_name="Description", blank=True, default="Пока данных нет"
    )
    termodate = models.BooleanField(default=False, verbose_name="Termo date")
    network_id = models.ManyToManyField("Network", verbose_name="Network")

    def __str__(self) -> str:
        if self.serial_num:
            return f"{self.designation}-{self.serial_num}"
        else:
            return f"{self.name}"

    def get_absolute_url(self):
        return reverse("project:device-detail", kwargs={"slug": self.slug})

    class Meta:
        db_table = "devices"
        verbose_name = "device"
        verbose_name_plural = "devices"


class FileDevice(models.Model):
    """
    The class describes the InstructionFile model
    """

    device_id = models.ForeignKey(
        Device,
        on_delete=models.CASCADE,
        verbose_name="Device",
        related_name="devices_files",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Date updated")
    file_configs = models.FileField(
        verbose_name="Файлы", upload_to=path_to_file_configs, blank=True
    )
    # file_configs = ProcessedImageField(
    #     upload_to = path_to_file_configs,
    #     verbose_name = 'Photo config',
    #     blank = True,
    #     options={'quantity': 100},
    #     format= 'JPEG',
    #     processors=[ResizeToFill(850, 380)]
    #     )

    def __str__(self) -> str:
        return f"{self.device_id.name}"

    class Meta:
        db_table = "file_device"
        verbose_name = "photo"
        verbose_name_plural = "photos"


class Network(models.Model):
    """
    The class describes the InstructionFile model
    """

    name = models.CharField(max_length=120, verbose_name="Name", db_index=True)
    slug = models.SlugField(max_length=120, verbose_name="URL", unique=True)
    description = models.TextField(verbose_name="Description", blank=True, default=" ")

    def __str__(self) -> str:
        return f"{self.name}"

    class Meta:
        db_table = "networks"
        verbose_name = "network"
        verbose_name_plural = "networks"


class Settings(models.Model):
    """
    The class describes the Settings model
    """

    class Speed(models.IntegerChoices):
        NOT_USED = 0
        S_1200 = 1200, "1200"
        S_2400 = 2400, "2400"
        S_4800 = 4800, "4800"
        S_9600 = 9600, "9600"
        S_19200 = 19200, "19200"
        S_38400 = 38400, "38400"
        S_57600 = 57600, "57600"
        S_115200 = 115200, "115200"

    class Paritet(models.TextChoices):
        NOT_USED = "-"
        EVEN = "E"
        NONE = "N"
        ODD = "O"

    class Bits(models.IntegerChoices):
        NOT_USED = 0
        SEVEN = 7, "7"
        EIGHT = 8, "8"
        NINE = 9, "9"

    class StopBit(models.IntegerChoices):
        NOT_USED = 0
        ONE = 1, "1"
        TWO = 2, "2"

    interface = models.ForeignKey(
        Network, verbose_name="Interface", on_delete=models.CASCADE
    )
    device = models.ForeignKey(
        Device,
        on_delete=models.CASCADE,
        verbose_name="Device",
        related_name="devices_settings",
    )
    slug = models.SlugField(
        max_length=50, verbose_name="URL", db_index=True, unique=True
    )
    slave_id = models.IntegerField(verbose_name="Slave ID", blank=True, null=True)
    speed = models.IntegerField(verbose_name="Speed", default=0, choices=Speed.choices)
    paritet = models.CharField(
        max_length=1, verbose_name="Paritet", default="-", choices=Paritet.choices
    )
    bit = models.IntegerField(verbose_name="Bits", default=0, choices=Bits.choices)
    stop_bit = models.IntegerField(
        verbose_name="Stop bit", default=0, choices=StopBit.choices
    )
    ip_address = models.CharField(
        max_length=15, verbose_name="IP address", default="not used"
    )
    mask = models.CharField(max_length=15, verbose_name="Mask", default="not used")
    gateway = models.CharField(
        max_length=15, verbose_name="Gateway", default="not used"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Date updated")
    description = models.TextField(verbose_name="Description", default=" ", blank=True)

    def __str__(self) -> str:
        return f"{self.interface} for {self.device}"

    class Meta:
        db_table = "settings"
        verbose_name = "setting"
        verbose_name_plural = "settings"


class WaveSensor(models.Model):
    """
    The class describes the WaveSensor model
    """

    device_id = models.ForeignKey(
        Device, on_delete=models.CASCADE, verbose_name="Binding", related_name="devices"
    )
    name_rkd = models.CharField(
        max_length=15, verbose_name="Desicn to RKD", db_index=True
    )  # обозначение по РКД
    description = models.CharField(
        max_length=80, verbose_name="Name equipment"
    )  # наименование оборудования
    group = models.CharField(max_length=30, verbose_name="Group")  # группа датчиков
    install = models.IntegerField(
        verbose_name="Column install"
    )  # установлено в колонне
    serial_number = models.CharField(
        max_length=30, verbose_name="Serial number"
    )  # серийный номер
    register = models.IntegerField(verbose_name="Register")  # регистр
    temp_warning = models.CharField(
        max_length=3, verbose_name="Temperature warning", default="85"
    )  # Предупреждение
    temp_error = models.CharField(
        max_length=3, verbose_name="Temperature over", default="90"
    )  # Перегрев

    def __str__(self) -> str:
        return f"{self.name_rkd}"

    class Meta:
        db_table = "wavesensors"
        verbose_name = "sensor"
        verbose_name_plural = "sensors"


class FileProject(models.Model):
    """ """

    project_id = models.ForeignKey(
        Project, on_delete=models.CASCADE, verbose_name="Проект", related_name="files"
    )
    name = models.CharField(verbose_name="Название", max_length=110, db_index=True)
    file = models.FileField(verbose_name="Файл", upload_to=path_to_file, blank=True)
    file_photos = models.ImageField(
        verbose_name="Photo", upload_to=path_to_file_report, blank=True  # type: ignore
    )
    # file_photos = ProcessedImageField(
    #     upload_to = path_to_file_report,
    #     verbose_name = 'Photo',
    #     blank = True,
    #     options={'quantity': 60},
    #     format= 'JPEG',
    #     processors=[ResizeToFill(310, 280, anchor=False)]
    #     )

    def __str__(self) -> str:
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse()  # type: ignore

    class Meta:
        db_table = "file_project"

documents/templates/product/base_product.html
{% load i18n static %}
{% load devices_tag %}


<div class="container overflow-hidden text-center mt-5 row">
    <table class="table_ caption-top" {% if searches %}style="margin-bottom: 100px;" {% endif %}>
        <thead class="table-light">
            <tr>
                <th scope="col">Проект</th>
                <th scope="col">Объект</th>
                <th scope="col">ID CRM</th>
                <th scope="col">Файлы</th>
                <th scope="col">Термомониторинг</th>
                <th scope="col"></th>
            </tr>
        </thead>
        {% for product in products %}
        {% with product.device_set.all as devices %}
        <tbody>
            <tr>
                <td>
                    <a class="project-link" href="{% url 'project:product-detail' product.slug %}">
                        {{ product.project }}
                    </a>
                </td>
                <td class="product-list">{{ product.company }}</td>
                <td>
                    {% url 'project:id_crm-detail' product.crm_id as crm_id_path %} <!--  Проверка url-address -->
                    {% if request.get_full_path == crm_id_path %} <!--  на текущей странице -->
                    {{ product.crm_id }}
                    {% else %}
                    <a class="project-link" href="{% url 'project:id_crm-detail' product.crm_id %}">
                        {{ product.crm_id }}
                    </a>
                    {% endif %}
                </td>
                <td>
                    <button type="button" class="btn btn-secondary py-0" data-bs-toggle="modal"
                        data-bs-target="#{{ product.project}}">
                        Подробнее
                    </button>
                    <!-- Модальное окно -->
                    <div class="modal fade" id="{{ product.project}}" data-bs-backdrop="static" data-bs-keyboard="false"
                        tabindex="-1" aria-labelledby="filesForProjectLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title auth-title fs-5" id="{{ product.project}}Label">Доступные
                                        файлы для проекта {{ product.project }}</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Закрыть"></button>
                                </div>
                                <div class="modal-body">
                                    {% with product.files.all as files %}
                                    {% if files %}
                                    {% for file in files %}
                                    <div class="container flex btn-justify">
                                        <span style="color: black !important;">{{ file.name }}</span>
                                        <a href="{{ file.file.url }}" download="">Скачать</a>
                                    </div>
                                    {% endfor %}
                                    {% else %}
                                    <span style="color: black !important;">Файлов пока не поступило</span>
                                    {% endif %}
                                    {% endwith %}
                                </div>
                                <div class="flex btn-justify modal-footer">
                                    {% if product.zip_archives %}
                                    <a href="{{ product.zip_archives.zip_archive.url }}" download="" type="button"
                                        class="btn btn-primary">
                                        Скачать архив
                                    </a>
                                    {% endif %}
                                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">OK</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td>
                    {% termo_date devices as termo %}
                    {% if termo %}
                    <div class="flex termo-check">
                        <input class="form-check-input icon-enable" type="checkbox" value=""
                            id="flexCheckCheckedDisabled" checked disabled>
                        <label class="form-check-label" for="flexCheckCheckedDisabled"></label>
                        {% else %}
                        <input class="form-check-input icon-disabled" type="checkbox" value=""
                            id="flexCheckIndeterminateDisabled" disabled>
                        <label class="form-check-label" for="flexCheckIndeterminateDisabled"></label>
                    </div>
                    {% endif %}
                </td>
                <td>
                    <a href="#">
                        <img style="display: none;" src="{% static 'access/icon/trash-solid.svg' %}" width="20px"
                            alt="">
                    </a>
                </td>
            </tr>
        </tbody>
        {% endwith %}
        {% endfor %}
    </table>
</div>

documents/templates/product/file_upload.html
{% extends 'base/base.html' %}
{% load i18n static %}
{% load photo_devices_tag %}

<!-- Хлебные крошки -->
{% block breadcrumbs %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'project:index' %}">Главная</a></li>
        <li class="breadcrumb-item active " aria-current="page"><a
                href="{% url 'project:id_crm-detail' product.crm_id %}">ID-CRM {{ product.crm_id }}</a></li>
        <li class="breadcrumb-item active " aria-current="page">{{ product.project }}</li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<div class="device-create">
    <div class="position-absolute top-50 start-50 translate-middle auth-content">
        <div class="signin-form ">
            <div class="modal-header auth-header">
                <h2 class="modal-title auth-title h4">{{ title }}</h2>
                <a style="padding: 15px" href="{% url 'project:index' %}" type="button"
                    class="btn-close position-absolute top-0 end-0"></a>
            </div>
            <!-- для мульти загрузки файлов в шаблон "base.html" добавлен скрипт -->
            <form method="post" class="form-auth" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    {% for field in form %}
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label_tag }}</label>
                    <p>{{ field }}</p>
                    {% if field.errors %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="flex form-footer">
                    <a class="btn btn-secondary" href="{% url 'project:product-detail' product.slug %}">Отмена</a>
                    <div class="form-help">
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

documents/templates/product/not_found.html
{% load i18n static %}

<div class="">
    <div class="position-absolute top-50 start-50 translate-middle auth-content">
        <div class="signin-form">
            <div class="modal-header auth-header">
                <h2 class="modal-title auth-title">Нет ни одного совпадения</h2>
                <a style="padding: 15px" href="{% url 'project:index' %}" type="button"
                    class="btn-close position-absolute top-0 end-0"></a>
            </div>
            <div class="form-auth">
                <div class="flex" style="justify-content: flex-end;">
                    <a type="button" class="btn btn-primary" href="{% url 'project:index' %}">Ясно</a>
                </div>
            </div>
        </div>
    </div>
</div>

documents/templates/product/product_crm.html
{% extends 'base/base.html' %}
{% load i18n static %}
{% load photo_devices_tag %}

<!-- Хлебные крошки -->
{% block breadcrumbs %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'project:index' %}">Главная</a></li>
        <li class="breadcrumb-item active " aria-current="page">ID-CRM {{ crm_id.first.crm_id }}</li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    <h2>ID-CRM {{ crm_id.first.crm_id }}</h2>
    {% if crm_id %}
        {% with crm_id as products %}
            {% include 'product/base_product.html' %}
        {% endwith %}
    {% else %}
        {% include 'product/not_found.html' %}
    {% endif %}
</div>
{% endblock %}

documents/templates/product/product_detail.html
{% extends 'base/base.html' %}
{% load i18n static %}
{% load photo_devices_tag %}

<!-- Хлебные крошки -->
{% block breadcrumbs %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'project:index' %}">Главная</a></li>
        <li class="breadcrumb-item active " aria-current="page"><a href="{% url 'project:id_crm-detail' product.crm_id %}">ID-CRM {{ product.crm_id }}</a></li>
        <li class="breadcrumb-item active " aria-current="page">{{ product.project }}</li>
    </ol>
</nav>
{% endblock %}

{% block content %}

<div class="container">
    <div class="flex instr-header">
        <h2>{{ product.project }}</h2>
        <div class="instr-title">
            {% if user.is_staff %}
            <a class="btn btn-secondary px-4" href="{% url 'project:add-files' product.slug %}">Добавить
                файлы</a>
            <a class="btn btn-secondary px-4" href="{% url 'project:device-create' product.slug %}">Добавить
                устройство</a>
            {% endif %}
        </div>
    </div>
    {% with product.device_set.all as devices %}
    {% if devices %}
    <table class="table_ table-light table-hover">
        <thead>
            <tr>
                <th scope="col">ID CRM</th>
                <th scope="col">Устройство</th>
                <th scope="col">Серийный №</th>
                <!-- <th scope="col">Скриншот</th> -->
                <th scope="col">Протокол</th>
                <th scope="col">Т °С</th>
                <th scope="col">Настройки</th>
            </tr>
        </thead>
        {% for device in product.device_set.all %}
        <tbody>
            <tr>
                <th scope="row">
                    {% url 'project:id_crm-detail' product.crm_id  as crm_id_path %} <!--  Проверка url-address -->
                    {% if request.get_full_path == crm_id_path %} <!--  на текущей странице -->
                        {{ product.crm_id }}
                    {% else %}
                    <a class="project-link" href="{% url 'project:id_crm-detail' product.crm_id %}">
                        {{ product.crm_id }}
                    </a>
                    {% endif %}
                </th>
                <td>
                    <a class="project-link" href="{% url 'project:device-detail' device.slug %}"
                        data-bs-toggle="tooltip" data-bs-placement="top" data-bs-custom-class="custom-tooltip"
                        data-bs-title="{{ device.name }} | {{ device.id}}">{{ device.designation }}</a>
                </td>
                <td>{{ device.serial_num }}</td>
                <!-- {% with device.devices_files.all as photos %}
                <td>
                    {% if photos %}
                    <a href="#">{{ device.devices_files.first }}</a>
                    {% else %}
                    not found
                    {% endif %}
                </td>
                {% endwith %} -->
                <td>{{ device.network_id.first }}</td>
                <td>{% if device.termodate %}
                    <img data-bs-toggle="tooltip" data-bs-placement="top" data-bs-custom-class="custom-tooltip"
                        title="Есть в термомонитооринге" src="{% static 'access/icon/check-yes.png' %}" width="25px"
                        alt="Есть">
                    {% else %}
                    <img data-bs-toggle="tooltip" data-bs-placement="top" data-bs-custom-class="custom-tooltip"
                        title="Нет в термомонитооринге" src="{% static 'access/icon/check-no.jpg' %}" width="25px"
                        alt="Нет">
                    {% endif %}
                </td>
                <td>
                    <div class="flex termo-check" data-bs-toggle="tooltip" data-bs-placement="top"
                        data-bs-custom-class="custom-tooltip" title="Сетевые настройки">
                        <a href="{% url 'project:device-detail' device.slug %}">
                            <img src="{% static 'access/icon/settings.svg' %}" width="25px" alt="">
                        </a>
                    </div>
                </td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    {% else %}
    {% include 'base/empty_data.html' %}
    {% endif %}
    {% endwith %}
    {{ photos_device }}
    {% photos_device product.id as photos %}
    {% with photos|random as photo_pk %}
    <div class="flex jc-centr">
        <div id="carouselExample" class="carousel slide" style="width: 50%;">
            <div class="carousel-inner">
                {% for photo in photos %}
                {% if photo %}
                <div class="carousel-item {% if photo.pk == photo_pk.pk %}active{% endif %}">
                    <div class="flex jc-centr">
                        <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#photosModal">
                            <img src="{{ photo.url }}" class="d-block" width="300px" alt="{{ photo }}">
                        </button>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Предыдущий</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Следующий</span>
            </button>
        </div>
    </div>
    <!-- Модальное окно -->
    <div class="modal fade" id="photosModal" tabindex="-1" aria-labelledby="photosModalLabel" aria-hidden="true">
        <div class="modal-dialog " style="max-width: 550px;">
            <div class="modal-content">
                <div class="modal-header">
                    <!-- <h1 class="modal-title fs-4" id="photosModalLabel">{{ photos|first }}</h1> -->
                    <button type="button" aria-label="+"></button>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                </div>
                <div class="modal-body">
                    <div id="fullModal" class="carousel slide">
                        <div class="carousel-inner">
                            {% for photo in photos %}
                            {% if photo %}
                            <div class="carousel-item {% if photo.pk == photo_pk.pk %}active{% endif %}">
                                <img src="{{ photo.url }}" class="d-block w-100" alt="{{ photo }}">
                            </div>
                            {% endif %}
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#fullModal" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Предыдущий</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#fullModal" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Следующий</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endwith %}
    
</div>

{% endblock %}

documents/templates/product/project_create.html
{% extends 'base/base.html' %}
{% load i18n static %}
{% load photo_devices_tag %}

<!-- Хлебные крошки -->
{% block breadcrumbs %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'project:index' %}">Главная</a></li>
        <li class="breadcrumb-item active " aria-current="page">Новый проект</li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<div class="device-create"> 
    <div class="position-absolute top-50 start-50 translate-middle auth-content">
        <div class="signin-form ">
            <div class="modal-header auth-header">
                <h2 class="modal-title auth-title h4">{{ title }}</h2>
                <a style="padding: 15px" href="{% url 'project:index' %}" type="button"
                    class="btn-close position-absolute top-0 end-0"></a>
            </div>
            {% include "form_create/form_create.html" %}
        </div>
    </div>
    </div>
{% endblock %}

documents/templates/product/search.html
{% extends 'base/base.html' %}
{% load i18n static %}
{% load devices_tag filters_tag %}

<!-- Хлебные крошки -->
{% block breadcrumbs %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'project:index' %}">Главная</a></li>
        <li class="breadcrumb-item active " aria-current="page">Поиск</li>
    </ol>
</nav>
{% endblock %}

{% block content %}
    <div class="container">
        <h2>{{ title }}</h2>
        {% if searches %}
            {% with searches|first as search %}
                {% if search|isinst:"Instructions" %}    
                    {% with searches as instructions %}
                        {% include 'documents/base_instruction.html' %}
                    {% endwith %}
                {% else %}            
                    {% with searches as products %}
                        {% include 'product/base_product.html' %}
                    {% endwith %}
                {% endif %}
            {% endwith %}
        {% else %}
            {% include 'product/not_found.html' %}
        {% endif %}
    </div>
{% endblock %}