documents/documents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("documents/doc-admin/", admin.site.urls),
    path("", include("instruction.urls")),
    path("manuals/", include("manuals.urls")),
    path("user/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    )
    urlpatterns.extend(
        static(settings.LOGGING_URL, document_root=settings.LOGGING_ROOT)
    )

documents/instruction/urls.py
from django.urls import path

from .views import (
    AddFileProjectView,
    CreateDeviceView,
    DeviceDetailView,
    IdCRMDetailView,
    InstructionFileView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectListView,
    SearchProjectView,
)

app_name = "project"

urlpatterns = [
    path("", ProjectListView.as_view(), name="index"),
    path(
        "product/<slug:slug>/detail", ProjectDetailView.as_view(), name="product-detail"
    ),
    path("product/create", ProjectCreateView.as_view(), name="product-create"),
    path(
        "product/<slug:slug>/add_files", AddFileProjectView.as_view(), name="add-files"
    ),
    path("id_crm/<int:crm_id>/detail", IdCRMDetailView.as_view(), name="id_crm-detail"),
    path(
        "product/<slug:slug>/create", CreateDeviceView.as_view(), name="device-create"
    ),
    path("device/<slug:slug>/detail", DeviceDetailView.as_view(), name="device-detail"),
    path("product/search", SearchProjectView.as_view(), name="search"),
    path("documents/instructions", InstructionFileView.as_view(), name="instructions"),
    # path('brand', BrandView.as_view(), name='brand-list'),
    # path('brand/<slug:slug>', BrandDetailView.as_view(), name='brand-detail'),
    # path('documents/instructions/add', AddedInstructionView.as_view(), name='instruction-add'),
]

documents/manuals/urls.py
from django.urls import path

from .views import BrandDetailView, BrandView

app_name = "manual"

urlpatterns = [
    path("", BrandView.as_view(), name="brand-list"),
    path("detail/<slug:slug>", BrandDetailView.as_view(), name="brand-detail"),
]

documents/users/urls.py
from django.urls import path

from .views import LoginUserView, LogoutUserView, RegisterUserView

app_name = "users"

urlpatterns = [
    path("login/", LoginUserView.as_view(), name="login"),
    path("logout/", LogoutUserView.as_view(), name="logout"),
    path("register/", RegisterUserView.as_view(), name="register"),
]

documents/manuals/models.py
from django.db import models
from django.urls import reverse


def path_to_file_instruction(instance: "FileModule", filename: str) -> str:
    """
    The function generates a path based on the name of the file with the instruction.

    :param instance: object File
    :param filename: name file
    :return: str - path to save
    """
    return f"files/{instance.name}/instruction/{filename}"


def path_to_file_manual(instance: "FileModule", filename: str) -> str:
    """
    The function generates a path based on the name of the file with the configs.

    :param instance: object File
    :param filename: name file
    :return: str - path to save
    """
    return f"files/{instance.name}/manuals/{filename}"


class Brand(models.Model):
    """
    The class describes the Brand model
    """

    name = models.CharField(max_length=100, verbose_name="Brand", db_index=True)
    slug = models.SlugField(max_length=100, verbose_name="URL", unique=True)

    def __str__(self) -> str:
        return f"{self.name}"

    class Meta:
        db_table = "brands"
        verbose_name = "brand"
        verbose_name_plural = "brands"


class Module(models.Model):
    """ """

    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name="Brand")
    name = models.CharField(max_length=80, verbose_name="Module", db_index=True)
    slug = models.SlugField(max_length=150, verbose_name="URL", unique=True)
    description = models.TextField(verbose_name="Description", blank=True, default=" ")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Date updated")

    def __str__(self) -> str:
        return f"{self.name}"

    class Meta:
        db_table = "modules"
        verbose_name = "module"
        verbose_name_plural = "modules"


class Instructions(models.Model):
    """
    The class describes the Instruction model
    """

    device = models.OneToOneField(
        Module, on_delete=models.CASCADE, verbose_name="Device"
    )
    name = models.CharField(max_length=120, verbose_name="Name", db_index=True)
    slug = models.SlugField(max_length=120, verbose_name="URL", unique=True)
    description = models.TextField(verbose_name="Description", blank=True, default=" ")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Date updated")

    def __str__(self) -> str:
        return f"{self.name}"

    class Meta:
        db_table = "instructions"
        verbose_name = "instruction"
        verbose_name_plural = "instructions"


class FileModule(models.Model):
    """
    The class describes the InstructionFile model
    """

    device = models.ForeignKey(
        Module,
        on_delete=models.CASCADE,
        verbose_name="Device",
        related_name="devices_files",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Date updated")
    file_instruction = models.FileField(
        upload_to=path_to_file_instruction, verbose_name="Инструкция", blank=True
    )
    file_manual = models.FileField(
        upload_to=path_to_file_manual, verbose_name="Руководство", blank=True
    )

    def __str__(self) -> str:
        return f"{self.device.name}"

    class Meta:
        db_table = "file_modules"
        verbose_name = "file"
        verbose_name_plural = "files"

documents/instruction/views.py
import logging
from itertools import chain
from typing import Any, Dict

from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView
from manuals.models import Module
from utils.format_name_uer import format_name

from .forms import AddFileForm, CreatedDeviceForm, CrerateprojectForm
from .models import Device, FileProject, Project

logger = logging.getLogger(__name__)


class ProjectListView(ListView):
    """
    The "ProjectListView" class displays a list of projects
    """

    model = Project
    template_name = "product/product_list.html"
    context_object_name = "products"

    def get_context_data(self, **kwargs: dict) -> Dict[str, Any]:
        context: dict = super().get_context_data(**kwargs)
        context.update(title="Network technologies")
        logger.info(f"`{format_name(self.request)}` - Рендеринг шаблона с Projects")
        return context

    def get_queryset(self):
        if not cache.get("products"):
            logger.warning("Отсутствует кэш для Projects")
            logger.info("Сформирован кэш для Projects")

        products = cache.get_or_set(
            "products", Project.objects.filter(archive=False).order_by("-created_at")
        )
        return products


class ProjectDetailView(DetailView):
    """ """

    model = Project
    template_name = "product/product_detail.html"
    context_object_name = "product"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = self.model.objects.get(slug=self.kwargs["slug"]).project
        context.update(title=f"{project} - Профиль")
        logger.info(
            f"`{format_name(self.request)}` - Загружена страница с детальной информацией о {project}"
        )
        return context


class ProjectCreateView(CreateView):
    """ """

    template_name = "product/project_create.html"
    form_class = CrerateprojectForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(title="Добавление проекта")
        logger.info("Рендеринг шаблона с формой добавления проекта")
        return context

    def form_valid(self, form):
        form.save()
        logger.info("Сохранена форма с добавлением проекта")
        return super().form_valid(form)


class AddFileProjectView(CreateView):
    """ """

    template_name = "product/file_upload.html"
    form_class = AddFileForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = Project.objects.get(slug=self.kwargs["slug"])
        context.update(title=f"Добавить файлы к проекту {product}", product=product)
        return context

    def form_valid(self, form):
        files = self.request.FILES.getlist("file")
        product = self.get_context_data().get("product")
        if not files:
            return self.form_invalid(form)

        for file in files:
            FileProject.objects.create(project_id=product, name=str(file), file=file)
        logger.info(f"Добавлены файлы к проекту - {product}")
        product.save()  # type: ignore
        logger.info(f"Сохранен проект - {product}. Для отчистки кэша")
        return HttpResponseRedirect(
            reverse_lazy("project:product-detail", kwargs={"slug": self.kwargs["slug"]})
        )


class IdCRMDetailView(ListView):
    """ """

    model = Project
    template_name = "product/product_crm.html"
    context_object_name = "crm_id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = self.model.objects.filter(crm_id=self.kwargs["crm_id"])
        title = f"ID-{str(products[0]).split('-')[0]}"
        context.update(title=title, current_path=self.request.META.get("HTTP_REFERER"))
        logger.info(
            f"`{format_name(self.request)}` - Получена детальная информация о `{title}`"
        )
        return context

    def get_queryset(self):
        products = Project.objects.filter(crm_id=self.kwargs["crm_id"])
        logger.info(
            f"`{format_name(self.request)}` - Получены проекты в кол-ве {len(products)} шт."
        )
        return products


class DeviceDetailView(DetailView):
    """ """

    model = Device
    template_name = "device/device_detail.html"
    context_object_name = "device"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        device = self.model.objects.get(slug=self.kwargs["slug"])
        context.update(title=f"{'device'} - Профиль")
        logger.info(
            f"`{format_name(self.request)}` - Получены данные о устройстве` "
            f"{device.name}-{device.serial_num}`"
        )
        return context


class SearchProjectView(ListView):
    """ """

    template_name = "product/search.html"
    context_object_name = "searches"
    # paginate_by = settings.get_paginate_by()
    allow_empty = True

    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
        except Exception as err:
            logger.warning(
                f"'{format_name(self.request)}` - По данному запросу ничего не найдено"
            )
            logger.exception(err)
            raise Http404("Poll does not exist")

        context.update(title=f"Результат поиска - {self.request.GET.get('search')}")
        logger.info(
            f"'{format_name(self.request)}` - Рендеринг шаблона поискового запроса"
        )
        return context

    def get_queryset(self):  # type: ignore
        not_found = "Нет ни одного совпадения"
        try:
            query = self.request.GET.get("search").upper()
            product = Project.objects.filter(
                Q(crm_id__icontains=query) | Q(project__icontains=query)
            )
            instruct = Module.objects.filter(Q(name__icontains=query))
            result = list(chain(product, instruct))
            try:
                if product[0].project.lower() == "no name":
                    raise ValidationError(not_found)
            except IndexError as err:
                logger.exception(err)

            if not result:
                logger.info(
                    f"'{format_name(self.request)}` - Результат поиска ...", not_found
                )
                raise ValidationError(not_found)

            logger.info(
                f"'{format_name(self.request)}` - Выполнен запрос поиска с вводной` "
                f"{self.request.GET.get('search')}`"
            )

            return result
        except Exception as err:
            logger.warning(f"'{format_name(self.request)}` - {not_found}")
            logger.exception(err)
            # messages.info(self.request, not_found)


class InstructionFileView(ListView):
    """ """

    template_name = "documents/instruction.html"
    context_object_name = "instructions"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(title="Инструкции")
        logger.info(
            f"`{format_name(self.request)}` - Загружена страница {context['title']}"
        )
        return context

    def get_queryset(self):
        if not cache.get("instructions"):
            logger.warning("Отсутствует кэш для Инструкций")
            logger.info("Сформирован кэш для Инструкций")

        instructions = cache.get_or_set("instructions", Module.objects.all())
        return instructions


# class BrandView(ListView):
#     """

#     """
#     template_name = 'brands/brand_list.html'
#     context_object_name = 'brands'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context.update(
#             title="Производители",
#         )

#         logger.info(f"`{format_name(self.request)}` - Загружена страница {context['title']}")
#         return context

#     def get_queryset(self):
#         if not cache.get('brands'):
#             logger.warning(f"Отсутствует кэш для модели Brand")
#             logger.info(f"Сформирован кэш для модели Brand")

#         brands = cache.get_or_set('brands', Brand.objects.all())
#         return brands


# class BrandDetailView(DetailView):
#     """

#     """
#     template_name = 'brands/brand_detail.html'
#     context_object_name = 'brand'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context.update(
#             title=f"Brand -{self.model.objects.get(slug=self.kwargs['slug']).name}"
#         )
#         logger.info(f"{format_name(self.request)}` - Загружена страница {context['title']}")

#         return context

#     def get_queryset(self):
#         brand = self.model.objects.get(slug=self.kwargs['slug']).name
#         logger.info(f"`{format_name(self.request)}` - Загружена детальная информация о {brand}")
#         return Brand.objects.get(slug=self.kwargs['slug'])


# class AddedInstructionView(CreateView):
#     """

#     """
#     model = Instructions
#     template_name = 'documents/add_instruction.html'
#     form_class = CreatedInstructionForms

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context.update(
#             title='Добавить инструкцию'
#         )
#         logger.info(f"Загружен шаблон с добавлением инструкции")
#         return context

#     def form_valid(self, form):
#         form.save()
#         logger.info(f"`{format_name(self.request)}` - Добавил инструкцию для "
#                     f"{self.request.POST.get('name')}")
#         return super().form_valid(form)

#     def get_absolute_url(self):
#         return reverse_lazy('project:instructions')


class CreateDeviceView(CreateView):
    """ """

documents/templates/documents/add_instruction.html
{% extends 'base/base.html' %}
{% load i18n static %}

{% block content %}
    <div class=""></div>
    <div class="position-absolute top-50 start-50 translate-middle auth-content">
        <div class="signin-form">
            <div class="modal-header auth-header">
                <h2 class="modal-title auth-title">{{ title }}</h2>
                <a style="padding: 15px" href="{% url 'project:instructions' %}" type="button"
                   class="btn-close position-absolute top-0 end-0"></a>
            </div>
            <form method="post" class="form-auth" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    {% for field in form %}
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label_tag }}</label>
                        <p>{{ field }}</p>
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="flex form-footer">
                    <a  href="{% url 'project:instructions' %}" class="btn btn-secondary">Отмена</a>
                    <div class="form-help">
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
{% endblock %}

documents/templates/documents/base_instruction.html
{% load i18n static %}
{% load devices_tag %}


<div class="overflow-hidden text-center mt-5 row">
    <table class="table table-light table-hover gy-5">
        <thead>
            <tr>
                <th scope="col">Бренд</th>
                <th scope="col">Имя устройства</th>
                <th scope="col">Название инструкции</th>
            </tr>
        </thead>
        {% for instruction in instructions %}
        <tbody>
            <tr>
                <td>{{ instruction.brand_id.name }}</td>
                <td>{{ instruction.device_id.name }}</td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle termo" type="button"
                            data-bs-toggle="dropdown" 
                            aria-expanded="false">
                            {{ instruction.name }}
                        </button>
                        <ul class="dropdown-menu">
                            {% if user.is_staff %}
                            <li><a class="dropdown-item" href="{{ instruction.docs.url }}" download="">Скачать</a>
                            </li>
                            <li><a class="dropdown-item" href="{{ instruction.docs.url }}"
                                    target="_blank">Читать</a></li>
                            {% else %}
                            <li><span class="dropdown-item">Скачать</span></li>
                            <li><span class="dropdown-item">Читать</span></li>
                            {% endif %}
                        </ul>
                    </div>
                </td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
</div>

documents/templates/documents/brand_detail.html
{% extends 'base/base.html' %}
{% load i18n static %}

<!-- Хлебные крошки -->
{% block breadcrumbs %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'project:index' %}">Главная</a></li>
            <li class="breadcrumb-item active " aria-current="page">
                <a href="{% url 'manual:brand-list' %}">
                    Производители
                </a>
            </li>
            <li class="breadcrumb-item active " aria-current="page">{{ brand }}</li>
        </ol>
    </nav>
{% endblock %}

{% block content %}
{% with brand.module_set.all as devices %}
    <div class="container">
        <div class="flex instr-header">
            <h2>{{ brand }}</h2>
            <div class="flex instr-title">
                {% if user.is_staff %}
                <button type="button" class="btn btn-secondary px-4" data-bs-toggle="modal" data-bs-target="#createDevice">Добавить устройство</button>
                {% endif %}
            </div>
        </div>
        {% if devices %}
            {% for device in devices %}

            {% endfor %}
        {% else %}
            {% include 'base/empty_data.html' %}
        {% endif %}
    </div>
{% endwith %}
    <!-- Модальное окно -->
    <div class="modal fade" id="createDevice" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="createDeviceLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h1 class="modal-title fs-5" id="createDeviceLabel">Заголовок модального окна</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
            ...
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            <button type="button" class="btn btn-primary">Понял</button>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

documents/templates/documents/brand_list.html
{% extends 'base/base.html' %}
{% load i18n static %}

<!-- Хлебные крошки -->
{% block breadcrumbs %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'project:index' %}">Главная</a></li>
        <li class="breadcrumb-item active " aria-current="page">{{ title }}</li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    <div class="flex instr-header">
        <h2>{{ title }}</h2>
        <div class="flex instr-title">
            <a class="btn btn-primary px-4" href="">Добавить</a>
            <a class="btn btn-primary px-4 ms-2" href="">Редактировать</a>
        </div>
    </div>
    <div class="row">
        <table class="table_ table-light table-hover">
            <thead class="table-light">
                <tr>
                    <th scope="col">Бренд</th>
                    <th scope="col">Имя устройства</th>
                    <th scope="col">Дополнительно</th>
                </tr>
            </thead>
            {% for brand in brands %}
            <tbody>
                <tr>
                    <th scope="row">
                        <a class="project-link" href="">{{ brand.name }}</a>
                    </th>
                    <td>{{ brand.module_set.first }}</td>
                    <td>
                        <a class="btn btn-secondary" href="{% url 'manual:brand-detail' brand.slug %}">Подробнее >></a>
                    </td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

documents/templates/documents/instructions.html
{% extends 'base/base.html' %}
{% load i18n static %}

<!-- Хлебные крошки -->
{% block breadcrumbs %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'project:index' %}">Главная</a></li>
        <li class="breadcrumb-item active " aria-current="page"><a
                href="#">Brand</a>
        </li>
        <li class="breadcrumb-item active " aria-current="page">{{ title }}</li>
    </ol>
</nav>
{% endblock %}

{% block content %}

{% endblock %}